export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INCREMENT_INGREDIENT_QUANTITY = 'INCREMENT_INGREDIENT_QUANTITY';
export const DECREMENT_INGREDIENT_QUANTITY = 'DECREMENT_INGREDIENT_QUANTITY';
export const SELECT_STORE = 'SELECT_STORE';
